import type { Metadata } from "next";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";

import StoryblokProvider from "@/components/StoryblokProvider";

import "./globals.css";
 
storyblokInit({
  accessToken: process.env.ACCESS_TOKEN,
  use: [apiPlugin]
});

export const metadata: Metadata = {
  title: "Storyblok Next App",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoryblokProvider>
  );
}
